name: CD
on:
  # Runs on all push events on main.
  push:
    branches: [main]

permissions:
  # Can only read the source code.
  contents: read

jobs:
  semver:
    name: Semver
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/semver
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          service-account-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          region: us-central1
          repository: mandelbrot
          service_name: mandelbrot
